const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * Release signing for the Play Store upload key.
 *
 * `android/` is regenerated by `expo prebuild`, so hand-editing
 * `android/app/build.gradle` does not survive. This plugin re-applies the
 * standard React Native release-signing block on every prebuild. The
 * credentials are read from Gradle properties (put them in
 * `~/.gradle/gradle.properties`, never in the repo — see `credentials/README.md`):
 *
 *   BREEZE_UPLOAD_STORE_FILE=/abs/path/breeze-upload.jks
 *   BREEZE_UPLOAD_STORE_PASSWORD=...
 *   BREEZE_UPLOAD_KEY_ALIAS=breeze-upload
 *   BREEZE_UPLOAD_KEY_PASSWORD=...
 *
 * When `BREEZE_UPLOAD_STORE_FILE` is not defined the release build type keeps
 * Expo's default (the debug keystore), so a contributor without the key can
 * still run `gradlew bundleRelease` for a local smoke test. `assembleRelease`
 * output signed with the debug key is rejected by Play, which is the intended
 * failure mode: it cannot be uploaded by mistake.
 */
const SIGNING_CONFIG = `
        release {
            if (project.hasProperty('BREEZE_UPLOAD_STORE_FILE')) {
                storeFile file(BREEZE_UPLOAD_STORE_FILE)
                storePassword BREEZE_UPLOAD_STORE_PASSWORD
                keyAlias BREEZE_UPLOAD_KEY_ALIAS
                keyPassword BREEZE_UPLOAD_KEY_PASSWORD
            }
        }`;

function applyUploadSigning(gradle) {
  if (gradle.includes('BREEZE_UPLOAD_STORE_FILE')) return gradle;

  // Expo's template declares `signingConfigs { debug { ... } }`; add ours after it.
  const debugBlock = /signingConfigs\s*\{\s*debug\s*\{[^}]*\}/;
  if (!debugBlock.test(gradle)) {
    throw new Error('withAndroidUploadSigning: signingConfigs.debug block not found in app/build.gradle');
  }
  gradle = gradle.replace(debugBlock, (match) => `${match}${SIGNING_CONFIG}`);

  // The template's release build type signs with the debug key by default.
  const releaseSigning = /(release\s*\{[^}]*?signingConfig\s+)signingConfigs\.debug/;
  if (!releaseSigning.test(gradle)) {
    throw new Error('withAndroidUploadSigning: buildTypes.release signingConfig not found in app/build.gradle');
  }
  return gradle.replace(
    releaseSigning,
    "$1project.hasProperty('BREEZE_UPLOAD_STORE_FILE') ? signingConfigs.release : signingConfigs.debug"
  );
}

module.exports = function withAndroidUploadSigning(config) {
  return withAppBuildGradle(config, (mod) => {
    mod.modResults.contents = applyUploadSigning(mod.modResults.contents);
    return mod;
  });
};

module.exports.applyUploadSigning = applyUploadSigning;
