import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { buildFallbackCspDirectives, relaxExistingCsp, resolveLocaleFromCookie, onRequest } from './middleware';
import { LOCALE_COOKIE_NAME } from './lib/appearance';

type MockLocals = { locale?: string };

function makeContext(cookieValue: string | undefined, acceptLanguage?: string) {
  return {
    cookies: {
      get: (name: string) => (name === LOCALE_COOKIE_NAME && cookieValue !== undefined ? { value: cookieValue } : undefined),
    },
    request: {
      headers: new Headers(acceptLanguage !== undefined ? { 'accept-language': acceptLanguage } : {}),
    },
    locals: {} as MockLocals,
  };
}

// #1023: Monaco is now self-hosted from /monaco/vs, so cdn.jsdelivr.net — a
// broad package-CDN gadget host — must no longer appear in any CSP directive.
// The directives Monaco/xterm actually need (style-src-elem 'unsafe-inline',
// worker-src blob:) must survive, just without the CDN token.
describe('CSP directives drop the jsdelivr CDN (#1023)', () => {
  const buildOptions = [
    { allowInlineScript: false, allowInlineStyle: false, isDev: false },
    { allowInlineScript: true, allowInlineStyle: true, isDev: false },
  ] as const;

  it.each(buildOptions)(
    'buildFallbackCspDirectives never emits cdn.jsdelivr.net (%o)',
    (options) => {
      const csp = buildFallbackCspDirectives(options);

      expect(csp).not.toContain('jsdelivr');
      // The Monaco/xterm runtime requirements still have to be present.
      expect(csp).toContain("style-src-elem 'self' 'unsafe-inline'");
      expect(csp).toContain("worker-src 'self' blob:");
      expect(csp).toMatch(/script-src 'self'/);
      // #1750: the auth-fetched quote PDF preview frames a blob: URL, so
      // frame-src must allow blob: (browsers don't fall back to img-src/
      // worker-src for an iframe source).
      expect(csp).toMatch(/frame-src[^;]*\bblob:/);
    }
  );

  it('relaxExistingCsp does not reintroduce the CDN when patching an Astro CSP', () => {
    const astroCsp =
      "default-src 'self'; script-src 'self' 'sha256-abc'; style-src 'self' 'sha256-def'";

    const patched = relaxExistingCsp(astroCsp, {
      allowInlineScript: false,
      allowInlineStyle: false,
    });

    expect(patched).not.toContain('jsdelivr');
    expect(patched).toContain("style-src-elem 'self' 'unsafe-inline'");
  });

  // The prod HTML CSP is generated by Astro's security.csp from the
  // script/style directives in astro.config.mjs — middleware.ts only patches
  // that header. Those directives aren't covered by the builder tests above, so
  // guard the file directly: a future edit re-adding the CDN there would ship a
  // jsdelivr allowance straight to prod.
  it('astro.config.mjs CSP source never references the jsdelivr CDN', () => {
    // vitest runs with cwd at the apps/web package root.
    const source = readFileSync(join(process.cwd(), 'astro.config.mjs'), 'utf8');

    expect(source).not.toContain('jsdelivr');
  });

  // #1750: astro.config.mjs's frame-src is the prod-authoritative directive for
  // HTML responses (middleware.ts never rewrites frame-src), and it's a
  // hand-maintained duplicate of resolveFrameSrcDirective in csp.ts. Guard the
  // file directly so dropping blob: from the frame-src Set here — which silently
  // re-breaks the quote PDF preview in prod while every other test stays green —
  // fails loudly. The match is scoped to the frame-src source Set (identified by
  // the docs origin) so it can't be satisfied by the blob: in worker-src/img-src.
  it('astro.config.mjs frameSrcDirective keeps blob: for the quote preview', () => {
    const source = readFileSync(join(process.cwd(), 'astro.config.mjs'), 'utf8');

    const frameSrcSet = source.match(/new Set\(\[[^\]]*docs\.breezermm\.com[^\]]*\]\)/);
    expect(frameSrcSet, 'frame-src source Set not found in astro.config.mjs').not.toBeNull();
    expect(frameSrcSet![0]).toContain("'blob:'");
  });
});

describe('locale cookie -> context.locals.locale', () => {
  it('accepts any of the 8 supported locales, not just en/pt-BR', () => {
    for (const locale of ['en', 'pt-BR', 'es-419', 'fr-FR', 'fr-CA', 'de-DE', 'it-IT', 'tr-TR']) {
      expect(resolveLocaleFromCookie(locale)).toBe(locale);
    }
  });

  it('rejects unsupported or missing cookie values', () => {
    expect(resolveLocaleFromCookie('fr')).toBeUndefined();
    expect(resolveLocaleFromCookie('klingon')).toBeUndefined();
    expect(resolveLocaleFromCookie(undefined)).toBeUndefined();
  });

  it('onRequest sets context.locals.locale from a valid breeze.locale cookie', async () => {
    const context = makeContext('fr-CA');
    await onRequest(context as any, async () => new Response('ok'));
    expect(context.locals.locale).toBe('fr-CA');
  });

  it('onRequest leaves context.locals.locale undefined for a missing or invalid cookie', async () => {
    const missing = makeContext(undefined);
    await onRequest(missing as any, async () => new Response('ok'));
    expect(missing.locals.locale).toBeUndefined();

    const invalid = makeContext('klingon');
    await onRequest(invalid as any, async () => new Response('ok'));
    expect(invalid.locals.locale).toBeUndefined();
  });

  // Maintainer follow-up on #5041: a browser-only signal must not be
  // invisible to the SSR shell just because the user never explicitly chose
  // a locale (no cookie yet).
  it('onRequest falls back to Accept-Language when there is no cookie', async () => {
    const context = makeContext(undefined, 'pt-BR,pt;q=0.9,en;q=0.8');
    await onRequest(context as any, async () => new Response('ok'));
    expect(context.locals.locale).toBe('pt-BR');
  });

  it('onRequest prefers the explicit cookie over Accept-Language', async () => {
    const context = makeContext('de-DE', 'pt-BR,pt;q=0.9');
    await onRequest(context as any, async () => new Response('ok'));
    expect(context.locals.locale).toBe('de-DE');
  });

  it('onRequest ignores an invalid cookie and still falls back to Accept-Language', async () => {
    const context = makeContext('klingon', 'fr-FR');
    await onRequest(context as any, async () => new Response('ok'));
    expect(context.locals.locale).toBe('fr-FR');
  });

  it('onRequest leaves locale undefined when neither cookie nor Accept-Language resolve', async () => {
    const context = makeContext(undefined, 'klingon,xx-XX');
    await onRequest(context as any, async () => new Response('ok'));
    expect(context.locals.locale).toBeUndefined();
  });
});
