import { sql } from 'drizzle-orm';
import { pgTable, uuid, varchar, timestamp, bigint, integer, boolean, jsonb, uniqueIndex, foreignKey, check } from 'drizzle-orm/pg-core';
import type { TopologyTargetDefinition, TopologyPolicyDefinition, TopologyDiagnosticPlan, TopologyDiagnosticStep } from '@breeze/shared';
import { topologyConfigTemplateVersions } from './topologyTemplates';
import { sites } from './orgs';
import { topologyNodes, topologyRelationships } from './topology';
import { networkMonitors } from './monitors';

// SQL owns DEFERRABLE INITIALLY IMMEDIATE, unavailable in Drizzle's FK builder.

export const topologyProbeTargets = pgTable('topology_probe_targets', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: uuid('org_id').notNull(),
  siteId: uuid('site_id').notNull(),
  partnerVersionId: uuid('partner_version_id').references(()=>topologyConfigTemplateVersions.id,{onDelete:'set null'}),
  orgVersionId: uuid('org_version_id').references(()=>topologyConfigTemplateVersions.id,{onDelete:'set null'}),
  configurationDigest: varchar('configuration_digest',{length:64}),
  key: varchar('key', { length: 64 }).notNull(),
  revision: bigint('revision', { mode: 'bigint' }).notNull().default(1n),
  label: varchar('label', { length: 255 }).notNull(),
  kind: varchar('kind', { length: 16 }).notNull(),
  definition: jsonb('definition').$type<TopologyTargetDefinition>().notNull(),
  enabled: boolean('enabled').notNull().default(false),
  createdBy: uuid('created_by'),
  updatedBy: uuid('updated_by'),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex('topology_probe_targets_id_org_site_uniq').on(t.id, t.orgId, t.siteId),
  foreignKey({ name: 'topology_probe_targets_site_fk', columns: [t.siteId,t.orgId], foreignColumns: [sites.id,sites.orgId] }).onDelete('cascade'),
  check('topology_probe_targets_kind_chk', sql`kind IN ('dns_name','tcp','https')`),
  check('topology_probe_targets_definition_chk', sql`jsonb_typeof(definition) = 'object' AND octet_length(definition::text) <= 262144`),
  check('topology_probe_targets_revision_chk', sql`revision >= 0`),
  uniqueIndex('topology_probe_targets_key_uniq').on(t.orgId, t.siteId, t.key),
]);

export const topologyMonitoringPolicies = pgTable('topology_monitoring_policies', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: uuid('org_id').notNull(),
  siteId: uuid('site_id').notNull(),
  partnerVersionId: uuid('partner_version_id').references(()=>topologyConfigTemplateVersions.id,{onDelete:'set null'}),
  orgVersionId: uuid('org_version_id').references(()=>topologyConfigTemplateVersions.id,{onDelete:'set null'}),
  configurationDigest: varchar('configuration_digest',{length:64}),
  key: varchar('key', { length: 64 }).notNull(),
  revision: bigint('revision', { mode: 'bigint' }).notNull().default(1n),
  enabled: boolean('enabled').notNull().default(false),
  definition: jsonb('definition').$type<TopologyPolicyDefinition>().notNull(),
  subjectNodeId: uuid('subject_node_id'),
  subjectRelationshipId: uuid('subject_relationship_id'),
  requesterId: uuid('requester_id'),
  authorityGeneration: bigint('authority_generation', { mode: 'bigint' }).notNull().default(0n),
  authorityDigest: varchar('authority_digest', { length: 64 }),
  activationIntent: boolean('activation_intent').notNull().default(false),
  lastScheduledAt: timestamp('last_scheduled_at', { withTimezone: true }),
  nextScheduledAt: timestamp('next_scheduled_at', { withTimezone: true }),
  blockedReason: varchar('blocked_reason', { length: 64 }),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex('topology_monitoring_policies_id_org_site_uniq').on(t.id, t.orgId, t.siteId),
  foreignKey({ name: 'topology_monitoring_policies_site_fk', columns: [t.siteId,t.orgId], foreignColumns: [sites.id,sites.orgId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_monitoring_policies_subject_node_id_fk', columns: [t.subjectNodeId,t.orgId,t.siteId], foreignColumns: [topologyNodes.id,topologyNodes.orgId,topologyNodes.siteId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_monitoring_policies_subject_relationship_id_fk', columns: [t.subjectRelationshipId,t.orgId,t.siteId], foreignColumns: [topologyRelationships.id,topologyRelationships.orgId,topologyRelationships.siteId] }).onDelete('cascade'),
  check('topology_monitoring_policies_definition_chk', sql`jsonb_typeof(definition) = 'object' AND octet_length(definition::text) <= 262144`),
  check('topology_monitoring_policies_subject_chk', sql`num_nonnulls(subject_node_id, subject_relationship_id) <= 1`),
  check('topology_monitoring_policies_revision_chk', sql`revision >= 0 AND authority_generation >= 0`),
  check('topology_monitoring_policies_authority_chk', sql`NOT enabled OR authority_digest IS NOT NULL`),
  uniqueIndex('topology_monitoring_policies_key_uniq').on(t.orgId, t.siteId, t.key),
]);

export const topologyPolicyTargets = pgTable('topology_policy_targets', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: uuid('org_id').notNull(),
  siteId: uuid('site_id').notNull(),
  policyId: uuid('policy_id').notNull(),
  targetId: uuid('target_id').notNull(),
  targetRevision: bigint('target_revision', { mode: 'bigint' }).notNull(),
  purpose: varchar('purpose', { length: 32 }).notNull(),
  position: integer('position').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex('topology_policy_targets_id_org_site_uniq').on(t.id, t.orgId, t.siteId),
  foreignKey({ name: 'topology_policy_targets_site_fk', columns: [t.siteId,t.orgId], foreignColumns: [sites.id,sites.orgId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_policy_targets_policy_id_fk', columns: [t.policyId,t.orgId,t.siteId], foreignColumns: [topologyMonitoringPolicies.id,topologyMonitoringPolicies.orgId,topologyMonitoringPolicies.siteId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_policy_targets_target_id_fk', columns: [t.targetId,t.orgId,t.siteId], foreignColumns: [topologyProbeTargets.id,topologyProbeTargets.orgId,topologyProbeTargets.siteId] }).onDelete('cascade'),
  check('topology_policy_targets_revision_chk', sql`target_revision >= 0 AND position >= 0`),
  uniqueIndex('topology_policy_targets_target_uniq').on(t.policyId, t.targetId, t.purpose),
]);

export const topologyMonitorBindings = pgTable('topology_monitor_bindings', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: uuid('org_id').notNull(),
  siteId: uuid('site_id').notNull(),
  nodeId: uuid('node_id'),
  relationshipId: uuid('relationship_id'),
  monitorId: uuid('monitor_id'),
  policyId: uuid('policy_id'),
  contextKey: varchar('context_key', { length: 255 }).notNull(),
  family: varchar('family', { length: 4 }).notNull(),
  originPolicy: jsonb('origin_policy').$type<{deviceId?: string; interfaceId?: string}>().notNull().default({}),
  metricRole: varchar('metric_role', { length: 64 }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex('topology_monitor_bindings_id_org_site_uniq').on(t.id, t.orgId, t.siteId),
  foreignKey({ name: 'topology_monitor_bindings_site_fk', columns: [t.siteId,t.orgId], foreignColumns: [sites.id,sites.orgId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_monitor_bindings_node_id_fk', columns: [t.nodeId,t.orgId,t.siteId], foreignColumns: [topologyNodes.id,topologyNodes.orgId,topologyNodes.siteId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_monitor_bindings_relationship_id_fk', columns: [t.relationshipId,t.orgId,t.siteId], foreignColumns: [topologyRelationships.id,topologyRelationships.orgId,topologyRelationships.siteId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_monitor_bindings_monitor_id_fk', columns: [t.monitorId,t.orgId,t.siteId], foreignColumns: [networkMonitors.id,networkMonitors.orgId,networkMonitors.siteId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_monitor_bindings_policy_id_fk', columns: [t.policyId,t.orgId,t.siteId], foreignColumns: [topologyMonitoringPolicies.id,topologyMonitoringPolicies.orgId,topologyMonitoringPolicies.siteId] }).onDelete('cascade'),
  check('topology_monitor_bindings_subject_chk', sql`num_nonnulls(node_id, relationship_id) = 1`),
  check('topology_monitor_bindings_owner_chk', sql`num_nonnulls(monitor_id, policy_id) >= 1`),
  check('topology_monitor_bindings_family_chk', sql`family IN ('ipv4','ipv6')`),
  check('topology_monitor_bindings_origin_chk', sql`jsonb_typeof(origin_policy) = 'object' AND octet_length(origin_policy::text) <= 8192`),
]);

export const topologyDiagnosticRuns = pgTable('topology_diagnostic_runs', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: uuid('org_id').notNull(),
  siteId: uuid('site_id').notNull(),
  recipeId: varchar('recipe_id', { length: 32 }).notNull(),
  recipeVersion: integer('recipe_version').notNull(),
  requesterId: uuid('requester_id').notNull(),
  subjectNodeId: uuid('subject_node_id'),
  subjectRelationshipId: uuid('subject_relationship_id'),
  subjectTargetId: uuid('subject_target_id'),
  originNodeId: uuid('origin_node_id').notNull(),
  originSnapshot: jsonb('origin_snapshot').$type<TopologyDiagnosticPlan['origin']>().notNull(),
  plan: jsonb('plan').$type<TopologyDiagnosticPlan>().notNull(),
  planDigest: varchar('plan_digest', { length: 64 }).notNull(),
  idempotencyKey: varchar('idempotency_key', { length: 255 }).notNull(),
  bodyHash: varchar('body_hash', { length: 64 }).notNull(),
  attemptId: uuid('attempt_id').notNull(),
  commandId: uuid('command_id'),
  state: varchar('state', { length: 16 }).notNull().default('queued'),
  assessment: varchar('assessment', { length: 16 }).notNull().default('unknown'),
  coverage: varchar('coverage', { length: 8 }).notNull().default('none'),
  reasons: jsonb('reasons').$type<string[]>().notNull().default([]),
  queuedAt: timestamp('queued_at', { withTimezone: true }).notNull().defaultNow(),
  startedAt: timestamp('started_at', { withTimezone: true }),
  queueDeadline: timestamp('queue_deadline', { withTimezone: true }).notNull(),
  deadline: timestamp('deadline', { withTimezone: true }).notNull(),
  finishedAt: timestamp('finished_at', { withTimezone: true }),
  cancelRequestedAt: timestamp('cancel_requested_at', { withTimezone: true }),
  failureReason: varchar('failure_reason', { length: 64 }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex('topology_diagnostic_runs_id_org_site_uniq').on(t.id, t.orgId, t.siteId),
  foreignKey({ name: 'topology_diagnostic_runs_site_fk', columns: [t.siteId,t.orgId], foreignColumns: [sites.id,sites.orgId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_diagnostic_runs_subject_node_id_fk', columns: [t.subjectNodeId,t.orgId,t.siteId], foreignColumns: [topologyNodes.id,topologyNodes.orgId,topologyNodes.siteId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_diagnostic_runs_subject_relationship_id_fk', columns: [t.subjectRelationshipId,t.orgId,t.siteId], foreignColumns: [topologyRelationships.id,topologyRelationships.orgId,topologyRelationships.siteId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_diagnostic_runs_subject_target_id_fk', columns: [t.subjectTargetId,t.orgId,t.siteId], foreignColumns: [topologyProbeTargets.id,topologyProbeTargets.orgId,topologyProbeTargets.siteId] }).onDelete('no action'),
  foreignKey({ name: 'topology_diagnostic_runs_origin_node_id_fk', columns: [t.originNodeId,t.orgId,t.siteId], foreignColumns: [topologyNodes.id,topologyNodes.orgId,topologyNodes.siteId] }).onDelete('cascade'),
  check('topology_diagnostic_runs_subject_chk', sql`num_nonnulls(subject_node_id, subject_relationship_id, subject_target_id) = 1`),
  check('topology_diagnostic_runs_state_chk', sql`state IN ('queued','running','completed','failed','cancelled','expired')`),
  check('topology_diagnostic_runs_assessment_chk', sql`assessment IN ('healthy','degraded','failed_check','unknown')`),
  check('topology_diagnostic_runs_coverage_chk', sql`coverage IN ('complete','partial','none')`),
  check('topology_diagnostic_runs_plan_chk', sql`jsonb_typeof(plan) = 'object' AND octet_length(plan::text) <= 262144`),
  check('topology_diagnostic_runs_origin_chk', sql`jsonb_typeof(origin_snapshot) = 'object' AND octet_length(origin_snapshot::text) <= 8192`),
  check('topology_diagnostic_runs_reasons_chk', sql`jsonb_typeof(reasons) = 'array' AND jsonb_array_length(reasons) <= 64`),
  check('topology_diagnostic_runs_deadline_chk', sql`deadline >= queue_deadline AND queue_deadline > queued_at`),
  uniqueIndex('topology_diagnostic_runs_request_uniq').on(t.orgId, t.siteId, t.requesterId, t.idempotencyKey),
]);

export const topologyDiagnosticSteps = pgTable('topology_diagnostic_steps', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: uuid('org_id').notNull(),
  siteId: uuid('site_id').notNull(),
  runId: uuid('run_id').notNull(),
  attemptId: uuid('attempt_id').notNull(),
  stepId: uuid('step_id').notNull(),
  commandId: uuid('command_id').notNull(),
  state: varchar('state', { length: 24 }).notNull(),
  result: jsonb('result').$type<TopologyDiagnosticStep>().notNull(),
  historicalOnly: boolean('historical_only').notNull().default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex('topology_diagnostic_steps_id_org_site_uniq').on(t.id, t.orgId, t.siteId),
  foreignKey({ name: 'topology_diagnostic_steps_site_fk', columns: [t.siteId,t.orgId], foreignColumns: [sites.id,sites.orgId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_diagnostic_steps_run_id_fk', columns: [t.runId,t.orgId,t.siteId], foreignColumns: [topologyDiagnosticRuns.id,topologyDiagnosticRuns.orgId,topologyDiagnosticRuns.siteId] }).onDelete('cascade'),
  check('topology_diagnostic_steps_state_chk', sql`state IN ('pending','running','succeeded','failed_check','timeout','unsupported','skipped','cancelled','execution_error')`),
  check('topology_diagnostic_steps_result_chk', sql`jsonb_typeof(result) = 'object' AND octet_length(result::text) <= 16384`),
  uniqueIndex('topology_diagnostic_steps_result_uniq').on(t.runId, t.attemptId, t.stepId),
]);
