import { sql } from 'drizzle-orm';
import { pgTable, uuid, varchar, timestamp, numeric, integer, doublePrecision, jsonb, primaryKey, uniqueIndex, index, foreignKey, check, type AnyPgColumn } from 'drizzle-orm/pg-core';
import type { CollectionOutcome, Lifecycle } from '@breeze/shared';
import { sites } from './orgs';
import { topologyNodes, topologyRelationships } from './topology';

// Producer counters are unsigned decimal strings. Server graph revisions remain bigint.
const sequence = (name: string) => numeric(name, { precision: 20, scale: 0 });
const time = (name: string) => timestamp(name, { withTimezone: true });
const scoped = () => ({ id: uuid('id').defaultRandom().notNull(), orgId: uuid('org_id').notNull(), siteId: uuid('site_id').notNull() });
const timestamps = () => ({ createdAt: time('created_at').notNull().defaultNow(), updatedAt: time('updated_at').notNull().defaultNow() });
const uint64 = (name: string, column: AnyPgColumn) => check(name, sql`${column} BETWEEN 0 AND 18446744073709551615`);

export const topologyInterfaces = pgTable('topology_interfaces', {
  ...scoped(),
  ownerNodeId: uuid('owner_node_id').notNull(),
  interfaceKey: varchar('interface_key', { length: 255 }).notNull(),
  epoch: varchar('epoch', { length: 255 }).notNull(),
  kind: varchar('kind', { length: 32 }).notNull().default('unknown'),
  role: varchar('role', { length: 64 }),
  name: varchar('name', { length: 255 }),
  alias: varchar('alias', { length: 255 }),
  osIndex: numeric('os_index', { precision: 10, scale: 0 }),
  addresses: jsonb('addresses').$type<unknown[]>().notNull().default([]),
  controllerPortKey: varchar('controller_port_key', { length: 255 }),
  parentInterfaceId: uuid('parent_interface_id'),
  lastObservedAt: time('last_observed_at'),
  lastOutcome: varchar('last_outcome', { length: 24 }).$type<CollectionOutcome>(),
  ...timestamps(),
}, t => [
  primaryKey({ columns: [t.id] }),
  uniqueIndex('topology_interfaces_scope_uniq').on(t.id, t.orgId, t.siteId),
  uniqueIndex('topology_interfaces_owner_scope_uniq').on(t.id, t.ownerNodeId, t.orgId, t.siteId),
  uniqueIndex('topology_interfaces_identity_uniq').on(t.ownerNodeId, t.interfaceKey, t.epoch),
  foreignKey({ name: 'topology_interfaces_site_fk', columns: [t.siteId, t.orgId], foreignColumns: [sites.id, sites.orgId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_interfaces_owner_fk', columns: [t.ownerNodeId, t.orgId, t.siteId], foreignColumns: [topologyNodes.id, topologyNodes.orgId, topologyNodes.siteId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_interfaces_parent_fk', columns: [t.parentInterfaceId, t.ownerNodeId, t.orgId, t.siteId], foreignColumns: [t.id, t.ownerNodeId, t.orgId, t.siteId] }),
  check('topology_interfaces_os_index_chk', sql`os_index BETWEEN 0 AND 4294967295`),
  check('topology_interfaces_addresses_chk', sql`jsonb_typeof(addresses) = 'array' AND jsonb_array_length(addresses) <= 1024 AND octet_length(addresses::text) <= 262144`),
]);

/** producerId is retained enrollment/collector identity, not a live inventory FK.
 * Moves/revocation fence the source; deleting inventory must retain its history. */
export const topologyCollectionSources = pgTable('topology_collection_sources', {
  ...scoped(),
  producerId: uuid('producer_id').notNull(),
  producerKind: varchar('producer_kind', { length: 24 }).notNull(),
  producerEpoch: varchar('producer_epoch', { length: 255 }).notNull(),
  epochIssuedAt: time('epoch_issued_at').notNull().defaultNow(),
  configurationRevision: varchar('configuration_revision', { length: 64 }).notNull().default('0'),
  protocol: varchar('protocol', { length: 32 }).notNull(),
  contextKey: varchar('context_key', { length: 255 }).notNull(),
  addressFamily: varchar('address_family', { length: 8 }).notNull().default('any'),
  acceptedSequence: sequence('accepted_sequence').notNull().default('0'),
  materializedSequence: sequence('materialized_sequence').notNull().default('0'),
  confirmedSequence: sequence('confirmed_sequence').notNull().default('0'),
  contentDigest: varchar('content_digest', { length: 64 }),
  publishedDigest: varchar('published_digest', { length: 64 }),
  digestVersion: integer('digest_version').notNull().default(1),
  baseSnapshotId: uuid('base_snapshot_id'),
  currentBaseline: jsonb('current_baseline').$type<Record<string, unknown>>().notNull().default({}),
  publishedBaseline: jsonb('published_baseline').$type<Record<string, unknown>>().notNull().default({}),
  pendingMisses: jsonb('pending_misses').$type<Record<string, unknown>>().notNull().default({}),
  firstBaselineAt: time('first_baseline_at'),
  lastFullValidationAt: time('last_full_validation_at'),
  confirmedThroughAt: time('confirmed_through_at'),
  freshUntil: time('fresh_until'),
  expectedIntervalSeconds: integer('expected_interval_seconds').notNull().default(300),
  lastOutcome: varchar('last_outcome', { length: 24 }).$type<CollectionOutcome>().notNull().default('not_attempted'),
  lastReceivedAt: time('last_received_at'),
  admissionTokens: doublePrecision('admission_tokens').notNull().default(2),
  admissionRefillAt: time('admission_refill_at').notNull().defaultNow(),
  quotaRejectedCount: integer('quota_rejected_count').notNull().default(0),
  retryCandidate: jsonb('retry_candidate').$type<Record<string, unknown>>(),
  revokedAt: time('revoked_at'),
  ...timestamps(),
}, t => [
  primaryKey({ columns: [t.id] }),
  uniqueIndex('topology_collection_sources_scope_uniq').on(t.id, t.orgId, t.siteId),
  uniqueIndex('topology_collection_sources_identity_uniq').on(t.orgId, t.siteId, t.producerKind, t.producerId, t.protocol, t.contextKey, t.addressFamily),
  index('topology_collection_sources_producer_idx').on(t.producerId, t.revokedAt),
  foreignKey({ name: 'topology_collection_sources_site_fk', columns: [t.siteId, t.orgId], foreignColumns: [sites.id, sites.orgId] }).onDelete('cascade'),
  uint64('topology_sources_accepted_sequence_chk', t.acceptedSequence),
  uint64('topology_sources_materialized_sequence_chk', t.materializedSequence),
  uint64('topology_sources_confirmed_sequence_chk', t.confirmedSequence),
  check('topology_sources_order_chk', sql`materialized_sequence <= accepted_sequence AND confirmed_sequence <= accepted_sequence`),
  check('topology_sources_admission_chk', sql`admission_tokens BETWEEN 0 AND 2`),
  check('topology_sources_family_chk', sql`address_family IN ('any','ipv4','ipv6')`),
  check('topology_sources_kind_chk', sql`producer_kind IN ('agent','snmp','unifi','discovery')`),
  check('topology_sources_bounds_chk', sql`expected_interval_seconds BETWEEN 30 AND 86400 AND quota_rejected_count >= 0 AND digest_version = 1`),
  check('topology_sources_baseline_chk', sql`jsonb_typeof(current_baseline) = 'object' AND octet_length(current_baseline::text) <= 1048576 AND jsonb_typeof(published_baseline) = 'object' AND octet_length(published_baseline::text) <= 1048576`),
  check('topology_sources_misses_chk', sql`jsonb_typeof(pending_misses) = 'object' AND octet_length(pending_misses::text) <= 524288`),
  check('topology_sources_retry_chk', sql`retry_candidate IS NULL OR (jsonb_typeof(retry_candidate) = 'object' AND octet_length(retry_candidate::text) <= 1048576)`),
]);

export const topologyCollectionRuns = pgTable('topology_collection_runs', {
  ...scoped(),
  sourceId: uuid('source_id').notNull(),
  producerId: uuid('producer_id').notNull(),
  producerEpoch: varchar('producer_epoch', { length: 255 }).notNull(),
  sequence: sequence('sequence').notNull(),
  snapshotId: uuid('snapshot_id').notNull(),
  contentDigest: varchar('content_digest', { length: 64 }).notNull(),
  digestVersion: integer('digest_version').notNull().default(1),
  parentJobId: uuid('parent_job_id'),
  parentCommandId: uuid('parent_command_id'),
  observedAt: time('observed_at').notNull(),
  effectiveAt: time('effective_at').notNull(),
  receivedAt: time('received_at').notNull().defaultNow(),
  outcome: varchar('outcome', { length: 24 }).$type<CollectionOutcome>().notNull(),
  completionScope: jsonb('completion_scope').$type<Record<string, unknown>>().notNull().default({}),
  snapshot: jsonb('snapshot').$type<Record<string, unknown>>().notNull(),
  rowCount: integer('row_count').notNull().default(0),
  omittedRowCount: integer('omitted_row_count').notNull().default(0),
  normalizedBytes: integer('normalized_bytes').notNull(),
  expectedIntervalSeconds: integer('expected_interval_seconds').notNull(),
  materializedAt: time('materialized_at'),
  ...timestamps(),
}, t => [
  primaryKey({ columns: [t.id] }),
  uniqueIndex('topology_collection_runs_scope_uniq').on(t.id, t.orgId, t.siteId),
  uniqueIndex('topology_collection_runs_sequence_uniq').on(t.sourceId, t.producerEpoch, t.sequence),
  index('topology_collection_runs_retention_idx').on(t.receivedAt),
  index('topology_collection_runs_budget_idx').on(t.orgId, t.producerId, t.receivedAt),
  foreignKey({ name: 'topology_collection_runs_site_fk', columns: [t.siteId, t.orgId], foreignColumns: [sites.id, sites.orgId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_collection_runs_source_fk', columns: [t.sourceId, t.orgId, t.siteId], foreignColumns: [topologyCollectionSources.id, topologyCollectionSources.orgId, topologyCollectionSources.siteId] }).onDelete('cascade'),
  uint64('topology_runs_sequence_chk', t.sequence),
  check('topology_runs_bounds_chk', sql`row_count >= 0 AND omitted_row_count >= 0 AND normalized_bytes BETWEEN 0 AND 1048576 AND expected_interval_seconds BETWEEN 30 AND 86400 AND digest_version = 1`),
  check('topology_runs_snapshot_chk', sql`jsonb_typeof(snapshot) = 'object' AND octet_length(snapshot::text) <= 1048576 AND jsonb_typeof(completion_scope) = 'object' AND octet_length(completion_scope::text) <= 65536`),
]);

export const topologyObservations = pgTable('topology_observations', {
  ...scoped(),
  runId: uuid('run_id').notNull(),
  observationKey: varchar('observation_key', { length: 255 }).notNull(),
  subjectNodeId: uuid('subject_node_id'),
  subjectInterfaceId: uuid('subject_interface_id'),
  relationshipId: uuid('relationship_id'),
  method: varchar('method', { length: 32 }).notNull(),
  evidenceClass: varchar('evidence_class', { length: 16 }).notNull(),
  attributes: jsonb('attributes').$type<Record<string, unknown>>().notNull(),
  observedAt: time('observed_at').notNull(),
  effectiveAt: time('effective_at').notNull(),
  receivedAt: time('received_at').notNull(),
  freshUntil: time('fresh_until').notNull(),
  withdrawnAt: time('withdrawn_at'),
  ...timestamps(),
}, t => [
  primaryKey({ columns: [t.id] }),
  uniqueIndex('topology_observations_scope_uniq').on(t.id, t.orgId, t.siteId),
  uniqueIndex('topology_observations_run_key_uniq').on(t.runId, t.observationKey),
  index('topology_observations_relationship_idx').on(t.orgId, t.siteId, t.relationshipId, t.effectiveAt),
  foreignKey({ name: 'topology_observations_site_fk', columns: [t.siteId, t.orgId], foreignColumns: [sites.id, sites.orgId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_observations_run_fk', columns: [t.runId, t.orgId, t.siteId], foreignColumns: [topologyCollectionRuns.id, topologyCollectionRuns.orgId, topologyCollectionRuns.siteId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_observations_node_fk', columns: [t.subjectNodeId, t.orgId, t.siteId], foreignColumns: [topologyNodes.id, topologyNodes.orgId, topologyNodes.siteId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_observations_interface_fk', columns: [t.subjectInterfaceId, t.subjectNodeId, t.orgId, t.siteId], foreignColumns: [topologyInterfaces.id, topologyInterfaces.ownerNodeId, topologyInterfaces.orgId, topologyInterfaces.siteId] }),
  foreignKey({ name: 'topology_observations_relationship_fk', columns: [t.relationshipId, t.orgId, t.siteId], foreignColumns: [topologyRelationships.id, topologyRelationships.orgId, topologyRelationships.siteId] }).onDelete('cascade'),
  check('topology_observations_interface_owner_chk', sql`subject_interface_id IS NULL OR subject_node_id IS NOT NULL`),
  check('topology_observations_attributes_chk', sql`jsonb_typeof(attributes) = 'object' AND octet_length(attributes::text) <= 262144`),
]);

export const topologyRelationshipSupport = pgTable('topology_relationship_support', {
  orgId: uuid('org_id').notNull(),
  siteId: uuid('site_id').notNull(),
  relationshipId: uuid('relationship_id').notNull(),
  sourceId: uuid('source_id').notNull(),
  latestObservationId: uuid('latest_observation_id'),
  producerEpoch: varchar('producer_epoch', { length: 255 }).notNull(),
  sequence: sequence('sequence').notNull(),
  contentDigest: varchar('content_digest', { length: 64 }).notNull(),
  firstPositiveAt: time('first_positive_at').notNull(),
  lastPositiveAt: time('last_positive_at').notNull(),
  effectiveAt: time('effective_at').notNull(),
  freshUntil: time('fresh_until').notNull(),
  completeMissCount: integer('complete_miss_count').notNull().default(0),
  lastMissSequence: sequence('last_miss_sequence'),
  lastMissAt: time('last_miss_at'),
  lifecycle: varchar('lifecycle', { length: 16 }).$type<Lifecycle>().notNull().default('active'),
  ...timestamps(),
}, t => [
  primaryKey({ columns: [t.relationshipId, t.sourceId] }),
  foreignKey({ name: 'topology_support_site_fk', columns: [t.siteId, t.orgId], foreignColumns: [sites.id, sites.orgId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_support_relationship_fk', columns: [t.relationshipId, t.orgId, t.siteId], foreignColumns: [topologyRelationships.id, topologyRelationships.orgId, topologyRelationships.siteId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_support_source_fk', columns: [t.sourceId, t.orgId, t.siteId], foreignColumns: [topologyCollectionSources.id, topologyCollectionSources.orgId, topologyCollectionSources.siteId] }).onDelete('cascade'),
  foreignKey({ name: 'topology_support_observation_fk', columns: [t.latestObservationId, t.orgId, t.siteId], foreignColumns: [topologyObservations.id, topologyObservations.orgId, topologyObservations.siteId] }),
  uint64('topology_support_sequence_chk', t.sequence),
  uint64('topology_support_miss_sequence_chk', t.lastMissSequence),
  check('topology_support_miss_count_chk', sql`complete_miss_count BETWEEN 0 AND 2`),
  check('topology_support_lifecycle_chk', sql`lifecycle IN ('active','withdrawn','archived')`),
]);
